# -*- coding: utf-8 -*-
"""Final IoT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxowwHYTPtzxhAJH0Ssi3GUuSdULMBrW
"""

!pip install influxdb-client pandas matplotlib

import pandas as pd
from influxdb_client import InfluxDBClient
import matplotlib.pyplot as plt

INFLUXDB_URL = "https://us-east-1-1.aws.cloud2.influxdata.com"
INFLUXDB_TOKEN = "JcKXoXE30JQvV9Ggb4-zv6sQc0Zh6B6Haz5eMRW0FrJEduG2KcFJN9-7RoYvVORcFgtrHR-Q_ly-52pD7IC6JQ=="
INFLUXDB_ORG = "0925ccf91ab36478"
INFLUXDB_BUCKET = "EXTREME_MANUFACTURING"

client = InfluxDBClient(url=INFLUXDB_URL, token=INFLUXDB_TOKEN, org=INFLUXDB_ORG)
query_api = client.query_api()

query_dht22 = '''
from(bucket: "EXTREME_MANUFACTURING")
  |> range(start: -2d, stop: -1d)
  |> filter(fn: (r) => r._measurement == "studio-dht22")
  |> filter(fn: (r) => r._field == "temperatura")
'''

tables_dht22 = query_api.query(org=INFLUXDB_ORG, query=query_dht22)
data_dht22 = []
for table in tables_dht22:
    for record in table.records:
        data_dht22.append((record.get_time(), record.get_field(), record.get_value()))

df_dht22 = pd.DataFrame(data_dht22, columns=["time", "field", "value"])
df_dht22 = df_dht22.pivot(index="time", columns="field", values="value")
df_dht22.plot(subplots=True, figsize=(10,6), title="Variables DHT22")
plt.show()